### ISSUE TITLE
报错http 500

### ISSUE THREAD

**Issue by ghost** [zhaohui8969/VST_NetProcess-#1]
TypeError: The view function for 'voiceChangeModel' did not return a valid response. The function either returned None or ended without a return statement.

studio one 5.3 win64，录音时可以正常监听、插件界面正常、开启插件后听不到耳返；每次说话有停顿后、flask接收到post请求，报错http 500，写入的音频文件为0字节。
我那个更新了flask_api，是照抄你的，只改了加载模型、推理部分，hubert.pt、G.pth放到根目录新建pth文件夹里就能用
是我哪部分没设置好吗

https://github.com/IceKyrin/sovits_f0_infer

[2022-10-10 19:20:22,012] [MainThread] [INFO] Loaded checkpoint './pth/152_epochs.pth' (iteration None)
[2022-10-10 19:20:22,147] [MainThread] [INFO]  * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:6842
 * Running on http://192.168.2.164:6842 (Press CTRL+C to quit)
[2022-10-10 19:20:24,319] [MainThread] [ERROR] Exception on /voiceChangeModel [POST]
Traceback (most recent call last):
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'voiceChangeModel' did not return a valid response. The function either returned None or ended without a return statement.
[2022-10-10 19:20:24,331] [MainThread] [INFO] 127.0.0.1 - - [10/Oct/2022 19:20:24] "[35m[1mPOST /voiceChangeModel HTTP/1.1[0m" 500 -
[2022-10-10 19:20:25,778] [MainThread] [ERROR] Exception on /voiceChangeModel [POST]
Traceback (most recent call last):
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'voiceChangeModel' did not return a valid response. The function either returned None or ended without a return statement.
[2022-10-10 19:20:25,779] [MainThread] [INFO] 127.0.0.1 - - [10/Oct/2022 19:20:25] "[35m[1mPOST /voiceChangeModel HTTP/1.1[0m" 500 -
[2022-10-10 19:20:34,760] [MainThread] [ERROR] Exception on /voiceChangeModel [POST]
Traceback (most recent call last):
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'voiceChangeModel' did not return a valid response. The function either returned None or ended without a return statement.
[2022-10-10 19:20:34,761] [MainThread] [INFO] 127.0.0.1 - - [10/Oct/2022 19:20:34] "[35m[1mPOST /voiceChangeModel HTTP/1.1[0m" 500 -
[2022-10-10 19:20:41,108] [MainThread] [ERROR] Exception on /voiceChangeModel [POST]
Traceback (most recent call last):
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'voiceChangeModel' did not return a valid response. The function either returned None or ended without a return statement.
[2022-10-10 19:20:41,110] [MainThread] [INFO] 127.0.0.1 - - [10/Oct/2022 19:20:41] "[35m[1mPOST /voiceChangeModel HTTP/1.1[0m" 500 -
[2022-10-10 19:20:44,351] [MainThread] [ERROR] Exception on /voiceChangeModel [POST]
Traceback (most recent call last):
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\xiaolang\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'voiceChangeModel' did not return a valid response. The function either returned None or ended without a return statement.
[2022-10-10 19:20:44,352] [MainThread] [INFO] 127.0.0.1 - - [10/Oct/2022 19:20:44] "[35m[1mPOST /voiceChangeModel HTTP/1.1[0m" 500 -

**Comment by ghost** [comment]
看了下model.py用的好像是colab的代码，那个有点老，直接保留下面这段就可以推理了；其余的都是长音频自动切分拼合用的，实时推理不会出现一分钟以上的片段。
或者直接用我刚改的，去掉model.py，在你的app.py改几句就能无缝换过去了（新加的flask_api.py）

source_path = "./wav_temp/input/" + file_name
                    audio, sample_rate = torchaudio.load(source_path)
                    input_size = audio.shape[-1]

                    sid = torch.LongTensor([int(speaker_id)]).to(self.dev)
                    soft = self.get_units(source_path).squeeze(0).cpu().numpy()
                    pitch = self.transcribe(source_path, soft.shape[0], tran)
                    pitch = torch.LongTensor(pitch).unsqueeze(0).to(self.dev)
                    stn_tst = torch.FloatTensor(soft)

                    with torch.no_grad():
                        x_tst = stn_tst.unsqueeze(0).to(self.dev)
                        x_tst_lengths = torch.LongTensor([stn_tst.size(0)]).to(self.dev)
                        audio = self.net_g_ms.infer(x_tst,
                                                    x_tst_lengths,
                                                    pitch,
                                                    sid=sid,
                                                    noise_scale=.667,
                                                    noise_scale_w=0.8,
                                                    length_scale=1)[0][
                            0, 0].data.float()

                    result_file_sample_rate = int(audio.shape[0] / input_size * 22050)
                    # if origin_sample_rate != result_file_sample_rate:
                    #     audio = torchaudio.transforms.Resample(orig_freq=result_file_sample_rate, new_freq=origin_sample_rate)(audio)[0]
                        # audio = torchaudio.functional.resample(audio, result_file_sample_rate, origin_sample_rate)
                    audio = audio.cpu().numpy()
                    soundfile.write("./wav_temp/output/" + file_name, audio, origin_sample_rate)

**Comment by ghost** [comment]
。。。新建了一个变量中转就能储存了，很奇怪。你原来的代码是直接fop.write(xxx.read())，但是我这不行

**Comment by zhaohui8969** [comment]
可能是莫名其妙的bug

**Comment by ghost** [comment]
佬，有空能不能打包个127.0.0.1:6842的release。我不会用c++，群里其他人用cmake打包出来的vst3不知道为什么宿主软件不识别。现在能正常运行，就是ip改host用着不太方便

**Comment by zhaohui8969** [comment]
打包Release版本的应该就能识别。有群？拉一下？

**Comment by ghost** [comment]
907879266
